#====================================================
name: MK-JoinMessage
main: me.mucloud.mcplugin.MK.JoinMessage.Main
version: SakuraOcean
versionCN: "樱·海"
verType: DEV
internalVersion: 1
author: Mu_Cloud
#====================================================
versionCNV: "§d§l樱§7§l·§3§l海"
versionV: "§d§lSakura§3§lOcean"
#====================================================
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.21"
  - "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.21"
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.21"
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.21"
#====================================================
api-version: 1.13
depend: [ PlaceholderAPI ]

commands:
  mkjm:
    aliases: [ mkjoinmessage ]
    usage: /mkjm info

permissions:
  mkjm.admin:
    default: op