#====================================================
name: MK-JoinMessage
main: me.mucloud.mcplugin.MK.JoinMessage.Main
version: SakuraOcean V2
versionCN: 樱花の海 · V2
internalVersion: 1
authors: [ Mu_Cloud ]
#====================================================
versionCNV: "§d樱花§7の§3海 §6§lV2"
versionV: "§dSakura§3Ocean §6§lV2"
#====================================================
softdepend: [ PlaceholderAPI ]
#====================================================
commands:
  mkjm:
    aliases: [ mkjoinmessage ]
    usage: /mkjm info
#====================================================
permissions:
  mkjm.admin:
    default: op
#====================================================