#==================================================
name: MK-JoinMessage
main: me.mucloud.plugin.MK.JoinMessage.Main
version: 1.1.2
author: Mu_Cloud
#==================================================
api-version: 1.12
depend: [ PlaceholderAPI ]

commands:
  mkjm:
    aliases: [ mkjoinmessage ]
    usage: /mkjs info

permissions:
  mkjs.admin:
    default: op